### ISSUE TITLE
Issue with ApplyPedBloodSpecific

### ISSUE THREAD

**Issue by loaf-scripts** [citizenfx/natives#978]
There seems to be an issue with the `ApplyPedBloodSpecific` native, it expects p8 to be a number when it should be a string. 

This is how I'm using it:
```lua
ApplyPedBloodSpecific(PlayerPedId(), 2, 0.35, 0.2, 0.0, 1.0, -1, 0.0, "BasicSlash")
```

This results in the error: 
```
SCRIPT ERROR: ApplyPedBloodSpecific.lua:4: bad argument #1 to '_ii' (number expected, got string)
> ApplyPedBloodSpecific (ApplyPedBloodSpecific.lua:4)
```

It's expecting p8 to be a number, but according to the native reference it has the type `Any`. I used it 2 years ago, with this code:
```lua
Citizen.InvokeNative(0xEF0D582CBF2D9B0F, PlayerPedId(), 2, 0.35, 0.2, 0.0, 1.0, -1, 0.0, "BasicSlash")
```
This no longer works, but doesn't give any errors either.

I have also tried using the hash for BasicSlash, but it didn't work either.

**Comment by 4mmonium** [comment]
What you're reporting is correct, last parameter should be a string, not a number. The game client then takes that string and converts it to a hash. The documentation for said [native](https://github.com/citizenfx/natives/blob/a06f864c21ea9d46a64fbe3212206fe778bdc495/PED/ApplyPedBloodSpecific.md?plain=1#L9) should be updated. `Any* p8` should be changed to `cs_type(Any*) char* particleName` or anything that fits the use case for said parameter.

Additionally, all the other parameters should also be updated since they're undocumented. I may review this native over the weekend.

**Comment by PsychoShock** [comment]
All param's should be:

## Parameters
* **ped**: Player ped index
* **p1**: component (int)
* **p2**: The UV texture coordinates determine the positioning of the decal within the designated area. (float)
* **p3**: The UV texture coordinates determine the positioning of the decal within the designated area. (float) 
* **p4**: rotation (float)
* **p5**: scale (float)
* **p6**: frame selection (int)
* **p7**: the number of seconds to pre-age (float)
* **p8**: bloodName

**Comment by PsychoShock** [comment]
@4mmonium This can probably be close since missing param's has been push!

**Comment by 4mmonium** [comment]
> @4mmonium This can probably be close since missing param's has been push!

Closing, thanks for notifying!
